version: '3.8'

services:
  service_1:
    image: parvezshaik645/service_1:v1
    expose: 
      - "8001"
    networks: 
      - reverseProxy
    healthcheck:
     test: ["CMD", "curl", "-fsS", "http://localhost:8001/ping"]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 5s
  
  service_2:
    image: parvezshaik645/service_2:v1
    expose:
      - "8002"
    networks: 
      - reverseProxy
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_PORT=8002
      - FLASK_ENV=production
    healthcheck:
     test: ["CMD","python","-c","import urllib.request; exit(0) if urllib.request.urlopen('http://localhost:8002/ping').getcode() == 200 else exit(1)" ]
     interval: 10s
     timeout: 5s
     retries: 3
     start_period: 5s



  nginx:
    image: nginx:1.23
    ports: 
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - service_1
      - service_2
    networks: 
      - reverseProxy

networks:
  reverseProxy:
    driver: bridge
